
name: PROD - Deploy Release

# Do this for every new release
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-example-cicd:$(git describe --tags --abbrev=0)
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-example-cicd:$(git describe --tags --abbrev=0)
